/// @file       LTAutoATC.h
/// @brief      Channel to AutoATC traffic
/// @see        https://autoatc.zem-solutions.com/
/// @details    Defines AutoATCConnection:\n
///             Takes AI traffic generated by AutoATC
/// @author     Birger Hoppe
/// @copyright  (c) 2025 Birger Hoppe
/// @copyright  Permission is hereby granted, free of charge, to any person obtaining a
///             copy of this software and associated documentation files (the "Software"),
///             to deal in the Software without restriction, including without limitation
///             the rights to use, copy, modify, merge, publish, distribute, sublicense,
///             and/or sell copies of the Software, and to permit persons to whom the
///             Software is furnished to do so, subject to the following conditions:\n
///             The above copyright notice and this permission notice shall be included in
///             all copies or substantial portions of the Software.\n
///             THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
///             IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
///             FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
///             AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
///             LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
///             OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
///             THE SOFTWARE.

#ifndef LTAutoATC_h
#define LTAutoATC_h

#include "LTChannel.h"

//
//MARK: AutoATC Constants
//
#define AATC_CHECK_NAME         "AutoATC Generated Traffic"
#define AATC_CHECK_URL          "https://autoatc.zem-solutions.com/Status.html"
#define AATC_CHECK_POPUP        "See AutoATC's status, but there is no list or map of flights"

#define AATC_NAME               "AutoATC"
#define AATC_URL                "https://load1.zem-solutions.com/AutoATCPeek?lat=%.4f&lon=%.4f"

#define AATC_RESULT             "result"            ///< expected to be "success", all else treated as failure
#define AATC_RESULT_SUCCESS     "success"
#define AATC_DATA               "data"              ///< array of aircraft
#define AATC_TIMESTAMP          "timestamp"         ///< when was the response compiled, used as timestamp for all positions

#define AATC_KEY                "ADS-B"
#define AATC_LAT                "lat"
#define AATC_LON                "lon"
#define AATC_ALT                "alt"
#define AATC_HEADING            "h"
#define AATC_GND                "ground"
#define AATC_CALL_SPOKEN        "cs"                ///< callsign as spoken, e.g. "air serbia 4139"
#define AATC_AC_TYPE            "af"
#define AATC_OP_ICAO            "icao"              ///< ICAO operator code

//
// MARK: SayIntentions connection class
//

/// Connection to AutoATC
class AutoATCConnection : public LTFlightDataChannel
{
public:
    AutoATCConnection ();                                   ///< Constructor
    std::string GetURL (const positionTy& pos) override;    ///< returns the URL to AutoATC traffic by position
    bool ProcessFetchedData () override;                    ///< Process response, forwarding to the processing queues
protected:
    void Main () override;                                  ///< virtual thread main function
};

#endif /* LTAutoATC_h */
